/// Flutter icons Summit
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Summit
///      fonts:
///       - asset: fonts/Summit.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Summit {
  Summit._();

  static const _kFontFam = 'Summit';
  static const String? _kFontPkg = null;

  static const IconData summitrocklogo = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
